### ISSUE TITLE
Integrate the slider in the menu instead of having it as a separate pop-up

### ISSUE THREAD

**Issue by romainrichard** [sidneys/desktop-dimmer#9]
I don't know if this is feasible but if it is I think it would improve usability.

Taking for example the Ubuntu sound menu:
![Ubuntu sound menu](https://2.bp.blogspot.com/-KLxFV-QKhw8/T6znCQRmULI/AAAAAAAAI54/RM3OqZdnoSE/s1600/sound-menu-all.png)

It would be nice to have the slider available after clicking on the Desktop Dimmer icon (i.e. without having to click on "Show" and then have the slider pop-up), just the way it works with the sound.

**Comment by romainrichard** [comment]
Now that I think about it, maybe a better solution would be not to have a menu and to instead bring up the slider with a single click on the Desktop Dimmer icon (if that's possible of course).

**Comment by sidneys** [comment]
@romainrichard 
Having these native slider controls would of course be the preferred choice, but Electron so far does not allow menu controls types other than labels, buttons and checkboxes (see [MenuItem](https://github.com/electron/electron/blob/master/docs/api/menu-item.md) API).

Your second suggestion can also not be implemented currently, due to upstream limitations with the native Electron Menu in Linux and the related libappindicator library on Ubuntu (see [here](https://github.com/maxogden/menubar/pull/40)).

Thus, this issue will have to remain a 'wontfix' for the time being, with implementations being carried out as soon as these upstream limitations disappear.
